name: Setup tests

runs:
    using: "composite"
    steps:
      - uses: actions/setup-python@v4
        with:
            python-version: '3.8'
            cache: 'pip'

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: firefox-geckodriver postgresql postgresql-contrib libimage-exiftool-perl
          version: 1.0

      - run: make web2py pydeps db.admin
        shell: bash

      - run: make install.selenium
        shell: bash
