name: Setup tests

runs:
    using: "composite"
    steps:
      - uses: actions/setup-python@v2
        with:
            python-version: '3.8'
            cache: 'pip'

      - run: |
          : divert chromedriver snap install so it is cached

          sudo add-apt-repository ppa:saiarcot895/chromium-beta
          sudo apt-get update
        shell: bash

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: chromium-chromedriver postgresql postgresql-contrib libimage-exiftool-perl
          version: 1.0

      - run: make web2py pydeps db.admin
        shell: bash

      - run: make install.selenium
        shell: bash
