#!/bin/bash -e

DIR=$(dirname $0)
SCRIPT=$1

SITE=$(basename $(dirname $DIR))

main() {

[ -f $DIR/$SCRIPT ] || {
	echo -e "usage: $0 <cron_task script>\n
	$DIR/$SCRIPT: script not found"
	exit 1
}

cd $DIR/../../..

python3 web2py.py --no_banner \
	-M \
	-S $SITE \
	-R applications/$SITE/cron_tasks/$SCRIPT

}

main &>> /tmp/$SITE.cron.output
