INSERT INTO "mail_templates"("hashtag","lang","subject","description","contents")
VALUES
(
E'#ReminderReviewerInvitationNewRoundRegisteredUser',
E'default',
E'{{appName}}: Invitation to review a new version of a preprint you have already reviewed - reminder',
E'Mail to user already registered to remind him/her that he/she has been invited as a reviewer',
E'<p>Dear {{destPerson}},</p>\n<p>This is a reminder concerning the following message, which you should already have received:</p>\n<p>I am handling the evaluation of the preprint entitled "{{art_title}}" (<a href="{{art_doi}}">{{art_doi}}</a>), for potential recommendation by {{description}} ({{longname}}).</p>\n<p>You have already evaluated this article as a reviewer in a previous round of review. This message is an invitation to review a new version of the preprint for a new round of evaluation.</p>\n<p>The evaluation process should guide the decision as to whether to ‘Revise’, ‘Recommend’ or ‘Reject’ the preprint. A preprint recommended by {{appLongName}} is a complete article that may be used and cited like any ‘classic’ article published in a peer-reviewed journal.</p>\n<p>If you have already reviewed a previous version of this MS, please consider this message as an invitation to review a new version of the preprint for a new round of evaluation.</p>\n<p>The evaluation process should guide the decision as to whether to ‘Revise’, ‘Recommend’ or ‘Reject’ the preprint. A preprint recommended by {{appLongname}} is a complete article that may be used and cited like any ‘classic’ article published in a peer-reviewed journals.</p>\n<p>If I eventually reach a favorable conclusion, all the editorial correspondence (reviews, recommender’s decisions, authors’ replies) and a recommendation text will be published by {{appLongname}}, under the license CC-BY-ND. If after one or several rounds of review, I eventually reject the preprint, the editorial correspondence (and specifically your review) will NOT be published. You will be notified by e-mail at each stage in the procedure.</p>\n<p>Note that to avoid any conflict of interests you should not accept to evaluate this preprint if the authors are close colleagues (people belonging to the same laboratory/unit/department in the last four years, people with whom they have published in the last four years, with whom they have received joint funding in the last four years, or with whom they are currently writing a manuscript, or submitting a grant proposal), or family members, friends, or anyone for whom bias might affect the nature of your evaluation.</p>\n<p>Please let me know as soon as possible whether you are willing to accept my invitation to review this revised version of this article, or whether you would prefer to decline, by clicking on the link below or by logging onto the {{appLongname}} website and going to \'For contributors —&gt; Invitation(s) to review a preprint\' in the top menu.</p>\n<p>Thanks in advance for your help.</p>\n<p>Yours sincerely,</p>\n<p>{{recommenderName}}.</p>\n<p>(Note that this message was automatically generated but I will also receive a copy of it)</p>'
),
(
E'#DefaultReviewInvitationNewRoundRegisteredUser',
E'default',
E'{{appName}}: Invitation to review a new version of a preprint you have already reviewed',
E'Mail to user already registered to indicate him/her that he/she is invited to re-review a preprint ',
E'<p>Dear {{destPerson}},</p>\n<p>I am handling the evaluation of the preprint entitled "{{art_title}}" (<a href="{{art_doi}}">{{art_doi}}</a>), for potential recommendation by {{description}} ({{longname}}).</p>\n<p>You have already evaluated this article as a reviewer in a previous round of review. This message is an invitation to review a new version of the preprint for a new round of evaluation.</p>\n<p>The evaluation process should guide the decision as to whether to ‘Revise’, ‘Recommend’ or ‘Reject’ the preprint. A preprint recommended by {{longname}} is a complete article that may be used and cited like any ‘classic’ article published in a peer-reviewed journal.</p>\n<p>If I eventually reach a favorable conclusion, all the editorial correspondence (reviews, recommender’s decisions, authors’ replies) and a recommendation text will be published by {{longname}}, under the license CC-BY-ND. If after one or several rounds of review, I eventually reject the preprint, the editorial correspondence (and specifically your review) will NOT be published. You will be notified by e-mail at each stage of the procedure.</p>\n<p>Please let me know as soon as possible whether you are willing to accept my invitation to review this revised version of this article, or whether you would prefer to decline, by clicking on the link below or by logging onto the {{longname}} website and going to \'For contributors —&gt; Invitation(s) to review a preprint\' in the top menu.</p>\n<p>Thanks in advance for your help.</p>\n<p>Yours sincerely,</p>\n<p>{{sender}}</p>'
);
