update mail_templates set contents = '
<p style="text-align: justify;">Dear Dr. {{LastName}},</p>
<p style="text-align: justify;"><span style="font-weight: 400;">This is an invitation to review for Peer Community In (PCI), a non-profit, non-commercial initiative, bolstered by the unwavering support of more than </span><a href="https://peercommunityin.org/pci-network/"><span style="font-weight: 400;">150 respected research organizations from over 20 countries</span></a><span style="font-weight: 400;">. Our goal is to put scientific publishing in the hands of the scientists themselves, making it available to everyone at no cost to readers or authors. Further details about PCI are available</span><a href="https://peercommunityin.org"><span style="font-weight: 400;"> </span><span style="font-weight: 400;">here</span></a><span style="font-weight: 400;">.</span></p>
<p style="text-align: justify;">I’m {{senderName}}, a researcher at {{Institution}} in {{country}}, and I’m proud to serve as an associate editor for {{description}} ({{longname}}).<br><br>An interesting manuscript, titled “<strong>{{art_title}}</strong>” and authored by {{authors}}, has been submitted to {{longname}}. Given your expertise in the field, I kindly request your assistance in evaluating this work.<br><br>You may access the manuscript for your review at: <a href="{{art_doi}}">{{art_doi}}</a></p>
<p style="text-align: justify;">If you accept the invitation to review this manuscript, you can choose to sign your review or remain anonymous. If you accept, I will expect to receive your review within {{reviewDuration}}, though extensions can be accommodated if needed.<br><br>Should the manuscript be accepted, your review will be published by {{longname}} under the CC-BY license, and I will write a short recommendation text explaining the article’s quality (i.e., why it was recommended). If the manuscript is rejected, reviews are not published (but are, of course, conveyed to the authors).</p>
<p style="text-align: justify;"><span style="font-weight: 400;">Once accepted via peer review, the article becomes a valid scientific study and transforms into a citable preprint. The authors can then opt to simply leave it on the preprint server as a PCI-recommended preprint. They can also decide to publish it directly in the<a href="https://peercommunityjournal.org"> Peer Community Journal</a> (Diamond Open Access) or submit it to one of the many<a href="https://peercommunityin.org/pci-friendly-journals/"> PCI-friendly journals</a> or to<a href="https://peercommunityin.org/pci-and-journals/"> any other journal of their choice,</a> with the link to the PCI evaluation process.</span><br><br><span style="font-weight: 400;">It’s important to note that you should not accept this invitation if you have any conflict of interest with the authors (i.e., if you were part of the same research team, regularly co-published, or shared joint funding during the last four years).<br><br>Kindly indicate your response using the buttons provided below (note that your login to {{longname}} is the email address that we used to contact you).<br><br>It’s possible that reviewing for PCI might not align with your current priorities or time constraints. Should this be the case, please rest assured that I fully comprehend your choice.<br><br>For any queries regarding the evaluation process or if you need additional information, please do not hesitate to contact me.<br><br>Thank you in advance for your help.<br><br>Best wishes,<br>{{sender}}</span></p>'
, subject = '{{appName}}: Invitation from {{senderName}} to review a manuscript'
where hashtag = '#DefaultReviewInvitationNewUser';

update mail_templates set contents = '
<p style="text-align: justify;">Dear Dr. {{LastName}},</p>
<p style="text-align: justify;"><span style="font-weight: 400;">This is an invitation to review for Peer Community In (PCI), a non-profit, non-commercial initiative, bolstered by the unwavering support of more than </span><a href="https://peercommunityin.org/pci-network/"><span style="font-weight: 400;">150 respected research organizations from over 20 countries</span></a><span style="font-weight: 400;">. Our goal is to put scientific publishing in the hands of the scientists themselves, making it available to everyone at no cost to readers or authors. Further details about PCI are available</span><a href="https://peercommunityin.org"><span style="font-weight: 400;"> </span><span style="font-weight: 400;">here</span></a><span style="font-weight: 400;">.</span></p>
<p style="text-align: justify;">I’m {{senderName}}, a researcher at {{Institution}} in {{country}}, and I’m proud to serve as an associate editor for {{description}} ({{longname}}).<br><br>An interesting manuscript, titled “<strong>{{art_title}}</strong>” and authored by {{authors}}, has been submitted to {{longname}}. Given your expertise in the field, I kindly request your assistance in evaluating this work.<br><br>You may access the manuscript for your review at: <a href="{{art_doi}}">{{art_doi}}</a></p>
<p style="text-align: justify;">If you accept the invitation to review this manuscript, you can choose to sign your review or remain anonymous. If you accept, I will expect to receive your review within {{reviewDuration}}, though extensions can be accommodated if needed.<br><br>Should the manuscript be accepted, your review will be published by {{longname}} under the CC-BY license, and I will write a short recommendation text explaining the article’s quality (i.e., why it was recommended). If the manuscript is rejected, reviews are not published (but are, of course, conveyed to the authors).</p>
<p style="text-align: justify;"><span style="font-weight: 400;">Once accepted via peer review, the article becomes a valid scientific study and transforms into a citable preprint. The authors can then opt to simply leave it on the preprint server as a PCI-recommended preprint. They can also decide to publish it directly in the<a href="https://peercommunityjournal.org"> Peer Community Journal</a> (Diamond Open Access) or submit it to one of the many<a href="https://peercommunityin.org/pci-friendly-journals/"> PCI-friendly journals</a> or to<a href="https://peercommunityin.org/pci-and-journals/"> any other journal of their choice,</a> with the link to the PCI evaluation process.</span><br><br><span style="font-weight: 400;">It’s important to note that you should not accept this invitation if you have any conflict of interest with the authors (i.e., if you were part of the same research team, regularly co-published, or shared joint funding during the last four years).<br><br>Kindly indicate your response using the buttons provided below (note that your login to {{longname}} is the email address that we used to contact you).<br><br>It’s possible that reviewing for PCI might not align with your current priorities or time constraints. Should this be the case, please rest assured that I fully comprehend your choice.<br><br>For any queries regarding the evaluation process or if you need additional information, please do not hesitate to contact me.<br><br>Thank you in advance for your help.<br><br>Best wishes,<br>{{sender}}</span></p>'
, subject = '{{appName}}: Invitation from {{senderName}} to review a manuscript'
where hashtag = '#DefaultReviewInvitationRegisteredUser';

update mail_templates set contents = '
<p><strong>A friendly reminder of my invitation to review.</strong><span style="font-weight: 400;"> I hope you can accept, but if for any reason you must decline, please be assured that I understand your decision. In any case, a response - by clicking on the buttons below - would be greatly appreciated.<br></span><span style="font-weight: 400;">{{message}}</span></p>
<p>&nbsp;</p>'
, subject = '{{appName}}: Invitation from {{senderName}} to review a manuscript - reminder'
where hashtag = '#ReminderReviewerReviewInvitationNewUser';

update mail_templates set contents = '
<p><strong>A friendly reminder of my invitation to review.</strong><span style="font-weight: 400;"> I hope you can accept, but if for any reason you must decline, please be assured that I understand your decision. In any case, a response - by clicking on the buttons below - would be greatly appreciated.<br></span><span style="font-weight: 400;">{{message}}</span></p>'
, subject = '{{appName}}: Invitation from {{senderName}} to review a manuscript - reminder'
where hashtag = '#ReminderReviewerReviewInvitationRegisteredUser';
