INSERT INTO "mail_templates"("hashtag","lang","subject","description","contents")
VALUES
(
E'#DefaultReviewInvitationNewRoundNewReviewerNewUser',
E'default',
E'{{appName}}: Invitation from {{senderName}} to review a manuscript',
E'Mail to user not yet registered to indicate them that they are invited to review a preprint',
E'Dear Dr {{LastName}}, My name is {{sender}}, I’m a researcher at {{Institution}}, {{country}}. I am also an associate editor for {{description}} ({{longname}}), i.e. I am a “recommender” for this organisation. As such, I am handling the evaluation of a manuscript recently submitted to {{longname}}: "{{art_title}}" by {{authors}}. One or several previous versions of this preprint have already been evaluated and appeared interesting. To strengthen the evaluation process, I would like to have your expert opinion on it. Would you agree to review it, possibly within {{reviewDuration}}? Extensions are possible if required, but please let us know if you need one. You can access and read over the manuscript here: {{art_doi}} I know that you surely receive many invitations to review manuscripts for publication, so why should you accept this one? By reviewing for PCI, you will be serving a community created by researchers to regain control over scholarly publication. We are a responsible, ethical, free, not-for-profit and non-commercial initiative, and we are supported by more than 150 research organizations worldwide. You can find more information on this initiative here. If you accept to review this manuscript, you can choose to sign your review or remain anonymous. If the article is accepted, your review will be published by {{longname}} under the CC-BY license and I will write a short recommendation text explaining the quality of the article (i,e., why it was recommended). If the article is rejected, reviews are not published (but are, of course, transmitted to the authors). If accepted, the article is considered a valid scientific study and becomes a citable preprint. The authors can choose to leave it on the preprint server as a PCI-recommended preprint, to publish it directly in the Peer Community Journal (in Diamond Open Access), or to submit it to one of the many PCI-friendly journals or to any other journal of their choice, with the link to the PCI evaluation process. You should not accept this invitation if you have any conflict of interest with the authors (i.e., if you were belonging to the same team in the last four years, you have had recurrent contacts to co-publish articles in the last four years, to receive joint funding in the last four years). Please let me know if you accept or decline this invitation by clicking on the corresponding button below. f you accept, please note that your review is expected within three weeks, but you can ask us for more time if needed. If you have any difficulty with the evaluation process or need additional information, please feel free to contact me. Thank you in advance for your help. Best wishes, {{sender}}'
);

INSERT INTO "mail_templates"("hashtag","lang","subject","description","contents")
VALUES
(
E'#DefaultReviewInvitationNewRoundNewReviewerRegisteredUser',
E'default',
E'{{appName}}: Invitation from {{senderName}} to review a manuscript',
E'Mail to registered user to invite them as new reviewer to make a new round of review of a preprint',
E'Dear Dr. {{LastName}}, This is an invitation to review for Peer Community In (PCI), a non-profit, non-commercial initiative, bolstered by the support of more than 150 respected research organizations from over 20 countries. A manuscript, titled “{{art_title}}” by {{authors}}, has been submitted to {{longname}} and is available here: {{art_doi}}. One or several previous versions of this preprint have already been evaluated and appeared interesting. To strengthen the evaluation process, I would like to have your expert opinion on it. Would you agree to review it, possibly within {{reviewDuration}}? Extensions are possible if required, but please let us know if you need one. If you accept the invitation, you can choose to sign your review or remain anonymous. Should the manuscript be accepted, your review will be published by {{longname}}, and I will write a short text explaining the article’s quality. If the manuscript is rejected, reviews are simply conveyed to the authors. Once accepted, the authors can then leave it on the preprint server as a PCI-recommended preprint. They can also decide to publish it directly in the Peer Community Journal (Diamond Open Access) or submit it for publication to one of the PCI-friendly journals. Importantly, you should not accept this invitation if you have any conflict of interest with the authors (i.e., if you were part of the same research team, regularly co-published, or shared joint funding during the last four years). Note that your login to {{longname}} is the email address that we used to contact you. It’s possible that reviewing for PCI might not align with your current priorities or time constraints. Should this be the case, please rest assured that I fully comprehend your choice. Thank you in advance for your help. Best wishes, {{sender}}, {{Institution}}, {{country}}'
);