delete from mail_templates where hashtag in (
	'#RecommenderDecisionSentBack'
);

INSERT INTO mail_templates (hashtag,lang,subject,description,contents) VALUES
	 ('#RecommenderDecisionSentBack','default','{{appName}}: You can edit your decision','Mail to recommender when a manager click on the red buton "Send back this decision to the recommender"','<p>Dear {{destPerson}},</p>
<p>We have changed the status of your decision on the article <span style="font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">by {{articleAuthors}} ({{articleDoi}}). Y</span>ou can now change or edit this decision. Before doing so, you can also invite more reviewers if needed.</p>
<p><span style="font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">T</span><span style="font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">o post your new decision on the PCI {{appName}} website, please:</span></p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">1) Go to <a href="{{linkTarget}}">{{linkTarget}}</a> or go to <a href="{{siteUrl}}">{{siteUrl}}</a></span><span style="font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">, log in and g</span><span style="font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">o to ''FOR RECOMMENDERS''—&gt; ''PREPRINT(S) YOU ARE HANDLING'' in the top menu. </span></p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">2) Click on the black ''VIEW/EDIT'' button at the right end of the corresponding line. </span></p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">3) Click on the black ''WRITE OR EDIT YOUR DECISION / RECOMMENDATION’ button. </span></p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">4) Indicate your decision by selecting ''I RECOMMEND THIS PREPRINT'', ''THIS PREPRINT MERITS REVISION'' or ''I REJECT THIS PREPRINT''. </span></p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">5) Choose a decision or recommendation title (this is of particular importance only for decisions to recommend the preprint concerned) and write or copy/paste your decision or recommendation text. </span></p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">-You can save a draft version of your decision or recommendation text by clicking on the blue ''SAVE'' button (you will then have to go through steps 0 to 5 to complete your decision or recommendation).&nbsp;</span></p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">6) To send your decision or recommendation to the managing board for validation, click on the green ''SAVE AND COMPLETE'' button. This will result in your decision or recommendation being sent to the managing board for validation.</span></p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">Thanks in advance.</span></p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">Best regards</span></p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">The Managing Board of PCI </span><span style="font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">{{appName}}</span></p>');
