delete from mail_templates where hashtag in (
'#ReminderReviewerReviewDueStage1',
'#ReminderReviewerReviewDueStage2',
'#ReminderReviewerReviewOverDueStage1',
'#ReminderReviewerReviewOverDueStage2',
'#ReminderReviewerReviewSoonDueStage1',
'#ReminderReviewerReviewSoonDueStage2'
);

INSERT INTO mail_templates (hashtag,lang,subject,description,contents) VALUES
(E'#ReminderReviewerReviewDueStage1',
	E'default',
	E'{{appName}}:  Review due - reminder',
	E'Mail to reviewer to indicate that a Stage 1 review is due',
	E'<p>Dear {{destPerson}},</p><p>This is an automated reminder that your review of the Stage 1 Registered Report entitled <strong>{{articleTitle}}</strong> by {{articleAuthors}} is due today.</p><p>We fully understand the challenges involved in meeting the huge number of deadlines we face on a daily basis. Because Stage 1 Registered Reports are reviewed prior to research being undertaken, delays in the review process can be particularly challenging for authors, so if you are unable to meet this deadine, we would be extremely grateful if you could let us know by replying to this email. Otherwise, many thanks in advance for writing your review.</p><p>To view, write, upload and manage your review, please follow this link <a href="{{linkTarget}}" data-mce-href="{{linkTarget}}">{{linkTarget}}</a> or log onto the {{appName}} website and go to ‘For contributors —&gt; Your reviews’ in the top menu.</p><p>Guidelines for reviewers of Registered Reports can be found <a href="https://rr.peercommunityin.org/help/guide_for_reviewers" data-mce-href="https://rr.peercommunityin.org/help/guide_for_reviewers">here</a>, including <a href="https://rr.peercommunityin.org/help/guide_for_reviewers#h_7586915642301613635089357" data-mce-href="https://rr.peercommunityin.org/help/guide_for_reviewers#h_7586915642301613635089357">specific tips for reviewing effectively</a>.</p><p>Thank you in advance for the time spent evaluating this submission. Reviewers are vital to the success of the <em>Peer Community In</em> initiative and we greatly appreciate your contribution.</p><p>Best wishes</p><p>The Managing Board of {{appName}}</p>')
,
(E'#ReminderReviewerReviewDueStage2',
	E'default',
	E'{{appName}}:  Review due - reminder',
	E'Mail to reviewer to indicate that a Stage 2 review is due',
	E'<p>Dear {{destPerson}},</p><p>This is an automated reminder that your review of the Stage 2 Registered Report entitled <strong>{{articleTitle}} </strong>is due today.</p><p>We fully understand the challenges involved in meeting the huge number of deadlines we face on a daily basis. If you are unable to meet this deadline, we would be extremely grateful if you could let us know by replying to this email. Otherwise, many thanks in advance for writing your review.</p><p>To view, write, upload and manage your review, please follow this link <a href="{{linkTarget}}" data-mce-href="{{linkTarget}}">{{linkTarget}}</a> or log onto the {{appName}} website and go to ‘For contributors —&gt; Your reviews’ in the top menu.</p><p>Guidelines for reviewers of Registered Reports can be found <a href="%20https://rr.peercommunityin.org/help/guide_for_reviewers" data-mce-href="%20https://rr.peercommunityin.org/help/guide_for_reviewers">here</a>, including <a href="https://rr.peercommunityin.org/help/guide_for_reviewers#h_7586915642301613635089357" data-mce-href="https://rr.peercommunityin.org/help/guide_for_reviewers#h_7586915642301613635089357">specific tips for reviewing effectively</a>.</p><p>Thank you in advance for the time spent evaluating this submission. Reviewers are vital to the success of the <em>Peer Community In</em> initiative and we greatly appreciate your contribution.</p><p>Best wishes</p><p>The Managing Board of {{appName}}</p>')
,
(E'#ReminderReviewerReviewOverDueStage1',
	E'default',
	E'{{appName}}:  Review overdue',
	E'Mail to reviewer to indicate that a Stage 1 review is overdue',
	E'<p>Dear {{destPerson}},</p><p>This is an automated reminder for your review of the Stage 1 Registered Report <strong>{{articleTitle}}</strong>&nbsp;by {{articleAuthors}} that was due a few days ago.</p><p>We fully understand the challenges involved in meeting review deadlines. Because Stage 1 Registered Reports are reviewed prior to research being undertaken, delays in the review process can present significant challenges for authors, so if you are unable to meet this deadline - or would prefer to withdraw from the review process - we would be extremely grateful if you could let us know by replying to this email.</p><p>To view, write, upload and manage your review, please follow this link <a href="{{linkTarget}}" data-mce-href="{{linkTarget}}">{{linkTarget}}</a> or log onto the {{appName}} website and go to ‘For contributors —&gt; Your reviews’ in the top menu. In case of any problem or difficulties with the website, please contact <a href="{{appContactMail}}" data-mce-href="{{appContactMail}}">{{appContactMail}}</a>.</p><p>Guidelines for reviewers of Registered Reports can be found <a href="%20https://rr.peercommunityin.org/help/guide_for_reviewers" data-mce-href="%20https://rr.peercommunityin.org/help/guide_for_reviewers">here</a>, including <a href="https://rr.peercommunityin.org/help/guide_for_reviewers#h_7586915642301613635089357" data-mce-href="https://rr.peercommunityin.org/help/guide_for_reviewers#h_7586915642301613635089357">specific tips for reviewing effectively</a>.</p><p>Thank you in advance for the time spent evaluating this submission. Reviewers are vital to the success of the <em>Peer Community In</em> initiative and we greatly appreciate your contribution.</p><p>Best wishes</p><p>The Managing Board of {{appName}}</p>')
,
(E'#ReminderReviewerReviewOverDueStage2',
	E'default',
	E'{{appName}}:  Review overdue',
	E'Mail to reviewer to indicate that a Stage 2 review is overdue',
	E'<p>Dear {{destPerson}},</p><p>This is an automated reminder that your review of the Stage 2 Registered Report entitled <strong>{{articleTitle}} </strong>was due a few days ago.</p><p>We fully understand the challenges involved in meeting review deadlines. Delays in the review process can present significant challenges for authors, so if you are unable to meet this deadline - or would prefer to withdraw from the review process - we would be extremely grateful if you could let us know by replying to this email.</p><p>To view, write, upload and manage your review, please follow this link <a href="{{linkTarget}}" data-mce-href="{{linkTarget}}">{{linkTarget}}</a> or log onto the {{appName}} website and go to ‘For contributors —&gt; Your reviews’ in the top menu. In case of any problem or difficulties with the website, please contact <a href="{{appContactMail}}" data-mce-href="{{appContactMail}}">{{appContactMail}}</a>.</p><p>Guidelines for reviewers of Registered Reports can be found <a href="%20https://rr.peercommunityin.org/help/guide_for_reviewers" data-mce-href="%20https://rr.peercommunityin.org/help/guide_for_reviewers">here</a>, including <a href="https://rr.peercommunityin.org/help/guide_for_reviewers#h_7586915642301613635089357" data-mce-href="https://rr.peercommunityin.org/help/guide_for_reviewers#h_7586915642301613635089357">specific tips for reviewing effectively</a>.</p><p>Thank you in advance for the time spent evaluating this submission. Reviewers are vital to the success of the <em>Peer Community In</em> initiative and we greatly appreciate your contribution.</p><p>Best wishes</p><p>The Managing Board of {{appName}}</p>')
,
(E'#ReminderReviewerReviewSoonDueStage1',
	E'default',
	E'{{appName}}:  Review due',
	E'Mail to reviewer to indicate that a Stage 1 review is soon due',
	E'<p>Dear {{destPerson}},</p><p>Thank you very much for agreeing to review the Stage 1 Registered Report by {{articleAuthors}} entitled <strong>{{articleTitle}}</strong> <a href="{{articleDoi}}" data-mce-href="{{articleDoi}}">{{articleDoi}}</a>. As a reminder, the review due date is {{reviewDueDate}}. If you are unable to meet this deadline, we would be very grateful if you could us know by replying to this email. Otherwise, many thanks in advance for writing your review.</p><p>To view, write, upload and manage your review, please follow this link <a href="{{linkTarget}}" data-mce-href="{{linkTarget}}">{{linkTarget}}</a> or log onto the {{appName}} website and go to ‘For contributors —&gt; Your reviews’ in the top menu.</p><p>When you have written or uploaded your review, you can:</p><p>1) save a draft version of your review for future modification by clicking on the ‘Save’ button; this allows you to make changes or to complete your review later;</p><p>or</p><p>2) save and submit your review by clicking on the ‘Save &amp; submit your review’ button.</p><p>If you have saved a draft version of your review, you can come back to it for modification or completion by clicking on ‘For contributors —&gt; Your reviews’ in the top menu, and then on the black ‘View/Edit’ button to the right on the corresponding line. Don’t forget to click on the ‘Save &amp; submit your review’ button to send your completed review to me.</p><p>Guidelines for reviewers of Registered Reports can be found <a href="%20https://rr.peercommunityin.org/help/guide_for_reviewers" data-mce-href="%20https://rr.peercommunityin.org/help/guide_for_reviewers">here</a>, including <a href="https://rr.peercommunityin.org/help/guide_for_reviewers#h_7586915642301613635089357" data-mce-href="https://rr.peercommunityin.org/help/guide_for_reviewers#h_7586915642301613635089357">specific tips for reviewing effectively</a>.</p><p>Thank you in advance for the time spent evaluating this submission. Reviewers are vital to the success of the <em>Peer Community In</em> initiative and we greatly appreciate your contribution.</p><p>Yours sincerely,</p><p>The Managing Board of {{appName}}</p>')
,
(E'#ReminderReviewerReviewSoonDueStage2',
	E'default',
	E'{{appName}}:  Review due',
	E'Mail to reviewer to indicate that a Stage 2 review is soon due',
	E'<p>Dear {{destPerson}},</p><p>Thank you for kindly agreeing to review the Stage 2 submission entitled <strong>{{articleTitle}}</strong> <a href="{{articleDoi}}" data-mce-href="{{articleDoi}}">{{articleDoi}}</a>. This is an automated reminder that we hope to receive your review before {{reviewDueDate}}. If this deadline is too short, please let us know as soon as possible. Otherwise, thank you in advance for writing your review before this deadline.</p><p>To view, write, upload and manage your review, please follow this link <a href="{{linkTarget}}" data-mce-href="{{linkTarget}}">{{linkTarget}}</a> or log onto the {{appName}} website and go to ‘For contributors —&gt; Your reviews’ in the top menu.</p><p>When you have written or uploaded your review, you can:</p><p>1) save a draft version of your review for future modification by clicking on the ‘Save’ button; this allows you to make changes or to complete your review later;</p><p>or</p><p>2) save and submit your review by clicking on the ‘Save &amp; submit your review’ button.</p><p>If you have saved a draft version of your review, you can come back to it for modification or completion by clicking on ‘For contributors —&gt; Your reviews’ in the top menu, and then on the black ‘View/Edit’ button to the right on the corresponding line. Don’t forget to click on the ‘Save &amp; submit your review’ button to send your completed review.</p><p>Guidelines for PCI reviewers can be found&nbsp;<a title="guideline for reviewers" href="https://peercommunityin.org/2020/10/22/pci-reviewer-guide/" target="_blank" rel="noopener" data-mce-href="https://peercommunityin.org/2020/10/22/pci-reviewer-guide/">here</a>.</p><p>Thanks in advance for the time spent evaluating this submission.</p><p>Yours sincerely,</p><p>The Managing Board of {{appName}}</p>')
;
